<?php

/**
 * @file
 * Contains vt_block.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function vt_block_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the vt_block module.
    case 'help.page.vt_block':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Custom blocks for Vox Teneo Site') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function vt_block_theme() {
  return [
    'homepage' => [
      'variables' => [
        'content' => NULL
      ],
      'render element' => 'children',
    ],
  ];
}
